version: '3'
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      USERNAME: "USERNAME"
      PASSWORD: "PASSWORD"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "100G" # Recommended: Stay under 200G total for Free Tier
      KVM: "N"         # This tells the container to skip the KVM check
    # devices:         <-- REMOVED
    #   - /dev/kvm     <-- REMOVED
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    stop_grace_period: 2m
